import type { EngineField } from "../engines";

export const DESIGN_GRAFIS_FIELDS: EngineField[] = [
  // 1. Brief & Kategori Universal
  {
    name: "brand",
    label: "Nama Brand / Bisnis / Klien",
    type: "text",
    group: "Brief Komersial",
    placeholder: "AuraSkin / Sudut Temu Cafe / AutoDetailing Pro / Event Organizer",
    required: true,
  },
  {
    name: "product",
    label: "Subjek Utama (Produk / Jasa / Kuliner / Event / Diskon)",
    type: "textarea",
    group: "Brief Komersial",
    placeholder: "Botol serum vitamin C / Jasa cuci mobil coating / Menu Wagyu Burger / Webinar AI 2026",
    required: true,
  },
  {
    name: "category",
    label: "Kategori & Niche Promosi",
    type: "text",
    group: "Brief Komersial",
    placeholder: "Skincare / Jasa & Layanan / F&B Kuliner / Fashion / Otomotif / Edukasi",
    required: true,
  },
  {
    name: "social_platform",
    label: "Platform Target Iklan",
    type: "select",
    group: "Brief Komersial",
    options: [
      "Instagram Feed Post (1:1 / 4:5)",
      "Instagram Stories / Reels (9:16)",
      "Marketplace Banner (Shopee / Tokopedia)",
      "Facebook Commercial Ad Banner",
      "Website Hero Banner (16:9)",
    ],
  },
  {
    name: "target_format",
    label: "Format Aspek Rasio Kanvas",
    type: "select",
    group: "Brief Komersial",
    options: ["1:1 (Square Feed)", "4:5 (Portrait Feed)", "9:16 (Stories / Reels)", "16:9 (Landscape)"],
  },
  {
    name: "slide_count",
    label: "Jumlah Halaman / Slide Desain Grafis (1 - 10 Slide)",
    type: "select",
    group: "Brief Komersial",
    options: [
      "1 Slide (Single Master Banner)",
      "2 Slide (Hook & Solution)",
      "3 Slide (Hook, Benefit & CTA)",
      "4 Slide (Problem, Solution, Proof, CTA)",
      "5 Slide (Full Mini Campaign)",
      "6 Slide (In-Depth Product Breakdown)",
      "7 Slide (Story & Transformation)",
      "8 Slide (Comprehensive Feature Matrix)",
      "9 Slide (Complete Grid / Series)",
      "10 Slide (Maximum Extended Story)",
    ],
    defaultValue: "1 Slide (Single Master Banner)",
  },

  // 2. Pesan Promosi & Copywriting
  {
    name: "headline",
    label: "Headline Utama Promosi (Text Locked in Quotes)",
    type: "text",
    group: "Pesan & Copywriting",
    placeholder: "PROMO SPESIAL GAJIAN / SOLUSI KULIT CERAH ALAMI",
    required: true,
  },
  {
    name: "copy",
    label: "Poin Keunggulan / Fitur Utama",
    type: "textarea",
    group: "Pesan & Copywriting",
    placeholder: "Diskon 50% khusus hari ini, gratis ongkir se-Indonesia, garansi uang kembali",
  },
  {
    name: "offer",
    label: "Penawaran / Harga / Voucher Diskon",
    type: "text",
    group: "Pesan & Copywriting",
    placeholder: "Hanya Rp 99.000 / Diskon Up To 70% / Buy 1 Get 1 Free",
  },
  {
    name: "cta",
    label: "Call to Action (CTA)",
    type: "text",
    group: "Pesan & Copywriting",
    placeholder: "BELI SEKARANG → / KLAIM VOUCHER / BOOKING JADWAL",
  },

  // 3. Visual & Negative Space Layout
  {
    name: "color",
    label: "Palet Warna Desain (Brand Colors)",
    type: "text",
    group: "Visual & Negative Space Layout",
    placeholder: "Emerald green #059669, soft gold accent #F59E0B, clean white #FFFFFF",
    required: true,
  },
  {
    name: "background",
    label: "Latar Belakang & Ruang Bersih (Negative Space)",
    type: "textarea",
    group: "Visual & Negative Space Layout",
    placeholder: "Clean studio backdrop dengan negative space 40% di bagian atas/kiri untuk penempatan teks promosi Canva",
    required: true,
  },
  {
    name: "product_photo",
    label: "Detail Subjek & Komposisi Posisi",
    type: "textarea",
    group: "Visual & Negative Space Layout",
    placeholder: "Subjek diletakkan di sepertiga kanan (Rule of Thirds), tajam, hyper-realistic, pencahayaan komersial",
  },
  {
    name: "lighting",
    label: "Pencahayaan Studio Komersial",
    type: "select",
    group: "Visual & Negative Space Layout",
    options: [
      "Commercial Studio Softbox (5200K Daylight)",
      "High-Key Cosmetic & Clean Advertising",
      "Dramatic Low-Key Moody Studio",
      "Warm Golden Sunlight Refraction",
      "Cyberpunk Neon Violet & Cyan Studio",
    ],
  },
  {
    name: "typography",
    label: "Gaya Tipografi Headline",
    type: "select",
    group: "Visual & Negative Space Layout",
    options: [
      "Modern Bold Neo-Grotesk (Swiss Design)",
      "Condensed Bold Commercial Headline",
      "High-End Editorial Luxury Serif",
      "Clean Minimalist Monospace",
    ],
  },
  {
    name: "additional_notes",
    label: "Instruksi Khusus Desain Grafis",
    type: "textarea",
    group: "Visual & Negative Space Layout",
    placeholder: "Pastikan ada area kosong tanpa noise untuk teks headline promosi.",
  },
];
