/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as CaptionsRouteImport } from './routes/captions'
import { Route as CarouselRouteImport } from './routes/carousel'
import { Route as CopyWritingRouteImport } from './routes/copy-writing'
import { Route as DemoGridRouteImport } from './routes/demo-grid'
import { Route as DesignGrafisRouteImport } from './routes/design-grafis'
import { Route as FaceCardAnalysisRouteImport } from './routes/face-card-analysis'
import { Route as FeedPortraitRouteImport } from './routes/feed-portrait'
import { Route as FeedSquareRouteImport } from './routes/feed-square'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as Grid9RouteImport } from './routes/grid-9'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoProdukRouteImport } from './routes/logo-produk'
import { Route as MenuFnbRouteImport } from './routes/menu-fnb'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReviewProdukRouteImport } from './routes/review-produk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TryOnProdukRouteImport } from './routes/try-on-produk'
import { Route as TypographyAdsRouteImport } from './routes/typography-ads'
import { Route as VideoStoryboardRouteImport } from './routes/video-storyboard'
import { Route as YoutubeThumbnailRouteImport } from './routes/youtube-thumbnail'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminGayaVisualRouteImport } from './routes/admin.gaya-visual'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPromoCreatorRouteImport } from './routes/admin.promo-creator'
import { Route as AdminPromoHistoryRouteImport } from './routes/admin.promo-history'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'
import { Route as ApiGeneratePromptRouteImport } from './routes/api/generate-prompt'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiRecommendBriefRouteImport } from './routes/api/recommend-brief'
import { Route as ApiTestKeyRouteImport } from './routes/api/test-key'
import { Route as ApiUploadGithubRouteImport } from './routes/api/upload-github'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BrandLogosIndexRouteImport } from './routes/brand-logos.index'
import { Route as BrandLogosIdRouteImport } from './routes/brand-logos.$id'
import { Route as BrandLogosCreateRouteImport } from './routes/brand-logos.create'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as VisualStylesIndexRouteImport } from './routes/visual-styles.index'
import { Route as VisualStylesIdRouteImport } from './routes/visual-styles.$id'
import { Route as VisualStylesCreateRouteImport } from './routes/visual-styles.create'
import { Route as AdminPromoResultIdRouteImport } from './routes/admin.promo-result.$id'
import { Route as ApiAdminAiChatRouteImport } from './routes/api/admin/ai-chat'
import { Route as ApiAdminBannerRouteImport } from './routes/api/admin/banner'
import { Route as ApiAdminGeneratePromoRouteImport } from './routes/api/admin/generate-promo'
import { Route as ApiAdminKeysRouteImport } from './routes/api/admin.keys'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminPricingRouteImport } from './routes/api/admin/pricing'
import { Route as ApiAdminTransactionsRouteImport } from './routes/api/admin/transactions'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminVouchersRouteImport } from './routes/api/admin/vouchers'
import { Route as ApiAiActiveConfigRouteImport } from './routes/api/ai.active-config'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiDbLogosRouteImport } from './routes/api/db/logos'
import { Route as ApiDbSettingsRouteImport } from './routes/api/db/settings'
import { Route as ApiDbVisualStylesRouteImport } from './routes/api/db/visual-styles'
import { Route as ApiPaymentsCreateCheckoutRouteImport } from './routes/api/payments/create-checkout'
import { Route as ApiPaymentsPackagesRouteImport } from './routes/api/payments/packages'
import { Route as ApiPaymentsStatusRouteImport } from './routes/api/payments/status'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiUserGalleryRouteImport } from './routes/api/user/gallery'
import { Route as ApiVouchersRedeemRouteImport } from './routes/api/vouchers/redeem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptionsRoute = CaptionsRouteImport.update({
  id: '/captions',
  path: '/captions',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselRoute = CarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyWritingRoute = CopyWritingRouteImport.update({
  id: '/copy-writing',
  path: '/copy-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGridRoute = DemoGridRouteImport.update({
  id: '/demo-grid',
  path: '/demo-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignGrafisRoute = DesignGrafisRouteImport.update({
  id: '/design-grafis',
  path: '/design-grafis',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceCardAnalysisRoute = FaceCardAnalysisRouteImport.update({
  id: '/face-card-analysis',
  path: '/face-card-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPortraitRoute = FeedPortraitRouteImport.update({
  id: '/feed-portrait',
  path: '/feed-portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSquareRoute = FeedSquareRouteImport.update({
  id: '/feed-square',
  path: '/feed-square',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const Grid9Route = Grid9RouteImport.update({
  id: '/grid-9',
  path: '/grid-9',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoProdukRoute = LogoProdukRouteImport.update({
  id: '/logo-produk',
  path: '/logo-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuFnbRoute = MenuFnbRouteImport.update({
  id: '/menu-fnb',
  path: '/menu-fnb',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewProdukRoute = ReviewProdukRouteImport.update({
  id: '/review-produk',
  path: '/review-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnProdukRoute = TryOnProdukRouteImport.update({
  id: '/try-on-produk',
  path: '/try-on-produk',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyAdsRoute = TypographyAdsRouteImport.update({
  id: '/typography-ads',
  path: '/typography-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoStoryboardRoute = VideoStoryboardRouteImport.update({
  id: '/video-storyboard',
  path: '/video-storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeThumbnailRoute = YoutubeThumbnailRouteImport.update({
  id: '/youtube-thumbnail',
  path: '/youtube-thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGayaVisualRoute = AdminGayaVisualRouteImport.update({
  id: '/admin/gaya-visual',
  path: '/admin/gaya-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoCreatorRoute = AdminPromoCreatorRouteImport.update({
  id: '/admin/promo-creator',
  path: '/admin/promo-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoHistoryRoute = AdminPromoHistoryRouteImport.update({
  id: '/admin/promo-history',
  path: '/admin/promo-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptRoute = ApiGeneratePromptRouteImport.update({
  id: '/api/generate-prompt',
  path: '/api/generate-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendBriefRoute = ApiRecommendBriefRouteImport.update({
  id: '/api/recommend-brief',
  path: '/api/recommend-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestKeyRoute = ApiTestKeyRouteImport.update({
  id: '/api/test-key',
  path: '/api/test-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadGithubRoute = ApiUploadGithubRouteImport.update({
  id: '/api/upload-github',
  path: '/api/upload-github',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandLogosIndexRoute = BrandLogosIndexRouteImport.update({
  id: '/brand-logos/',
  path: '/brand-logos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandLogosIdRoute = BrandLogosIdRouteImport.update({
  id: '/brand-logos/$id',
  path: '/brand-logos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandLogosCreateRoute = BrandLogosCreateRouteImport.update({
  id: '/brand-logos/create',
  path: '/brand-logos/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualStylesIndexRoute = VisualStylesIndexRouteImport.update({
  id: '/visual-styles/',
  path: '/visual-styles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualStylesIdRoute = VisualStylesIdRouteImport.update({
  id: '/visual-styles/$id',
  path: '/visual-styles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualStylesCreateRoute = VisualStylesCreateRouteImport.update({
  id: '/visual-styles/create',
  path: '/visual-styles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoResultIdRoute = AdminPromoResultIdRouteImport.update({
  id: '/admin/promo-result/$id',
  path: '/admin/promo-result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiChatRoute = ApiAdminAiChatRouteImport.update({
  id: '/api/admin/ai-chat',
  path: '/api/admin/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBannerRoute = ApiAdminBannerRouteImport.update({
  id: '/api/admin/banner',
  path: '/api/admin/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGeneratePromoRoute = ApiAdminGeneratePromoRouteImport.update({
  id: '/api/admin/generate-promo',
  path: '/api/admin/generate-promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKeysRoute = ApiAdminKeysRouteImport.update({
  id: '/api/admin/keys',
  path: '/api/admin/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingRoute = ApiAdminPricingRouteImport.update({
  id: '/api/admin/pricing',
  path: '/api/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTransactionsRoute = ApiAdminTransactionsRouteImport.update({
  id: '/api/admin/transactions',
  path: '/api/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVouchersRoute = ApiAdminVouchersRouteImport.update({
  id: '/api/admin/vouchers',
  path: '/api/admin/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiActiveConfigRoute = ApiAiActiveConfigRouteImport.update({
  id: '/api/ai/active-config',
  path: '/api/ai/active-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbLogosRoute = ApiDbLogosRouteImport.update({
  id: '/api/db/logos',
  path: '/api/db/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbSettingsRoute = ApiDbSettingsRouteImport.update({
  id: '/api/db/settings',
  path: '/api/db/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbVisualStylesRoute = ApiDbVisualStylesRouteImport.update({
  id: '/api/db/visual-styles',
  path: '/api/db/visual-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateCheckoutRoute =
  ApiPaymentsCreateCheckoutRouteImport.update({
    id: '/api/payments/create-checkout',
    path: '/api/payments/create-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPackagesRoute = ApiPaymentsPackagesRouteImport.update({
  id: '/api/payments/packages',
  path: '/api/payments/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsStatusRoute = ApiPaymentsStatusRouteImport.update({
  id: '/api/payments/status',
  path: '/api/payments/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGalleryRoute = ApiUserGalleryRouteImport.update({
  id: '/api/user/gallery',
  path: '/api/user/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVouchersRedeemRoute = ApiVouchersRedeemRouteImport.update({
  id: '/api/vouchers/redeem',
  path: '/api/vouchers/redeem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/brand-kit': typeof BrandKitRoute
  '/captions': typeof CaptionsRoute
  '/carousel': typeof CarouselRoute
  '/copy-writing': typeof CopyWritingRoute
  '/demo-grid': typeof DemoGridRoute
  '/design-grafis': typeof DesignGrafisRoute
  '/face-card-analysis': typeof FaceCardAnalysisRoute
  '/feed-portrait': typeof FeedPortraitRoute
  '/feed-square': typeof FeedSquareRoute
  '/gallery': typeof GalleryRoute
  '/grid-9': typeof Grid9Route
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logo-produk': typeof LogoProdukRoute
  '/menu-fnb': typeof MenuFnbRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-produk': typeof ReviewProdukRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/try-on-produk': typeof TryOnProdukRoute
  '/typography-ads': typeof TypographyAdsRoute
  '/video-storyboard': typeof VideoStoryboardRoute
  '/youtube-thumbnail': typeof YoutubeThumbnailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gaya-visual': typeof AdminGayaVisualRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promo-creator': typeof AdminPromoCreatorRoute
  '/admin/promo-history': typeof AdminPromoHistoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recommend-brief': typeof ApiRecommendBriefRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/upload-github': typeof ApiUploadGithubRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand-logos/$id': typeof BrandLogosIdRoute
  '/brand-logos/create': typeof BrandLogosCreateRoute
  '/result/$id': typeof ResultIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/visual-styles/$id': typeof VisualStylesIdRoute
  '/visual-styles/create': typeof VisualStylesCreateRoute
  '/brand-logos/': typeof BrandLogosIndexRoute
  '/visual-styles/': typeof VisualStylesIndexRoute
  '/admin/promo-result/$id': typeof AdminPromoResultIdRoute
  '/api/admin/ai-chat': typeof ApiAdminAiChatRoute
  '/api/admin/banner': typeof ApiAdminBannerRoute
  '/api/admin/generate-promo': typeof ApiAdminGeneratePromoRoute
  '/api/admin/keys': typeof ApiAdminKeysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/transactions': typeof ApiAdminTransactionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/vouchers': typeof ApiAdminVouchersRoute
  '/api/ai/active-config': typeof ApiAiActiveConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/db/logos': typeof ApiDbLogosRoute
  '/api/db/settings': typeof ApiDbSettingsRoute
  '/api/db/visual-styles': typeof ApiDbVisualStylesRoute
  '/api/payments/create-checkout': typeof ApiPaymentsCreateCheckoutRoute
  '/api/payments/packages': typeof ApiPaymentsPackagesRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/user/gallery': typeof ApiUserGalleryRoute
  '/api/vouchers/redeem': typeof ApiVouchersRedeemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/brand-kit': typeof BrandKitRoute
  '/captions': typeof CaptionsRoute
  '/carousel': typeof CarouselRoute
  '/copy-writing': typeof CopyWritingRoute
  '/demo-grid': typeof DemoGridRoute
  '/design-grafis': typeof DesignGrafisRoute
  '/face-card-analysis': typeof FaceCardAnalysisRoute
  '/feed-portrait': typeof FeedPortraitRoute
  '/feed-square': typeof FeedSquareRoute
  '/gallery': typeof GalleryRoute
  '/grid-9': typeof Grid9Route
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logo-produk': typeof LogoProdukRoute
  '/menu-fnb': typeof MenuFnbRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-produk': typeof ReviewProdukRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/try-on-produk': typeof TryOnProdukRoute
  '/typography-ads': typeof TypographyAdsRoute
  '/video-storyboard': typeof VideoStoryboardRoute
  '/youtube-thumbnail': typeof YoutubeThumbnailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gaya-visual': typeof AdminGayaVisualRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promo-creator': typeof AdminPromoCreatorRoute
  '/admin/promo-history': typeof AdminPromoHistoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recommend-brief': typeof ApiRecommendBriefRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/upload-github': typeof ApiUploadGithubRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand-logos/$id': typeof BrandLogosIdRoute
  '/brand-logos/create': typeof BrandLogosCreateRoute
  '/result/$id': typeof ResultIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/visual-styles/$id': typeof VisualStylesIdRoute
  '/visual-styles/create': typeof VisualStylesCreateRoute
  '/brand-logos': typeof BrandLogosIndexRoute
  '/visual-styles': typeof VisualStylesIndexRoute
  '/admin/promo-result/$id': typeof AdminPromoResultIdRoute
  '/api/admin/ai-chat': typeof ApiAdminAiChatRoute
  '/api/admin/banner': typeof ApiAdminBannerRoute
  '/api/admin/generate-promo': typeof ApiAdminGeneratePromoRoute
  '/api/admin/keys': typeof ApiAdminKeysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/transactions': typeof ApiAdminTransactionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/vouchers': typeof ApiAdminVouchersRoute
  '/api/ai/active-config': typeof ApiAiActiveConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/db/logos': typeof ApiDbLogosRoute
  '/api/db/settings': typeof ApiDbSettingsRoute
  '/api/db/visual-styles': typeof ApiDbVisualStylesRoute
  '/api/payments/create-checkout': typeof ApiPaymentsCreateCheckoutRoute
  '/api/payments/packages': typeof ApiPaymentsPackagesRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/user/gallery': typeof ApiUserGalleryRoute
  '/api/vouchers/redeem': typeof ApiVouchersRedeemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/brand-kit': typeof BrandKitRoute
  '/captions': typeof CaptionsRoute
  '/carousel': typeof CarouselRoute
  '/copy-writing': typeof CopyWritingRoute
  '/demo-grid': typeof DemoGridRoute
  '/design-grafis': typeof DesignGrafisRoute
  '/face-card-analysis': typeof FaceCardAnalysisRoute
  '/feed-portrait': typeof FeedPortraitRoute
  '/feed-square': typeof FeedSquareRoute
  '/gallery': typeof GalleryRoute
  '/grid-9': typeof Grid9Route
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logo-produk': typeof LogoProdukRoute
  '/menu-fnb': typeof MenuFnbRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/review-produk': typeof ReviewProdukRoute
  '/settings': typeof SettingsRoute
  '/stories': typeof StoriesRoute
  '/try-on-produk': typeof TryOnProdukRoute
  '/typography-ads': typeof TypographyAdsRoute
  '/video-storyboard': typeof VideoStoryboardRoute
  '/youtube-thumbnail': typeof YoutubeThumbnailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/gaya-visual': typeof AdminGayaVisualRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/promo-creator': typeof AdminPromoCreatorRoute
  '/admin/promo-history': typeof AdminPromoHistoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/generate-prompt': typeof ApiGeneratePromptRoute
  '/api/media': typeof ApiMediaRoute
  '/api/recommend-brief': typeof ApiRecommendBriefRoute
  '/api/test-key': typeof ApiTestKeyRoute
  '/api/upload-github': typeof ApiUploadGithubRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/brand-logos/$id': typeof BrandLogosIdRoute
  '/brand-logos/create': typeof BrandLogosCreateRoute
  '/result/$id': typeof ResultIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/visual-styles/$id': typeof VisualStylesIdRoute
  '/visual-styles/create': typeof VisualStylesCreateRoute
  '/brand-logos/': typeof BrandLogosIndexRoute
  '/visual-styles/': typeof VisualStylesIndexRoute
  '/admin/promo-result/$id': typeof AdminPromoResultIdRoute
  '/api/admin/ai-chat': typeof ApiAdminAiChatRoute
  '/api/admin/banner': typeof ApiAdminBannerRoute
  '/api/admin/generate-promo': typeof ApiAdminGeneratePromoRoute
  '/api/admin/keys': typeof ApiAdminKeysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/transactions': typeof ApiAdminTransactionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/vouchers': typeof ApiAdminVouchersRoute
  '/api/ai/active-config': typeof ApiAiActiveConfigRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/db/logos': typeof ApiDbLogosRoute
  '/api/db/settings': typeof ApiDbSettingsRoute
  '/api/db/visual-styles': typeof ApiDbVisualStylesRoute
  '/api/payments/create-checkout': typeof ApiPaymentsCreateCheckoutRoute
  '/api/payments/packages': typeof ApiPaymentsPackagesRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/user/gallery': typeof ApiUserGalleryRoute
  '/api/vouchers/redeem': typeof ApiVouchersRedeemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/brand-kit'
    | '/captions'
    | '/carousel'
    | '/copy-writing'
    | '/demo-grid'
    | '/design-grafis'
    | '/face-card-analysis'
    | '/feed-portrait'
    | '/feed-square'
    | '/gallery'
    | '/grid-9'
    | '/history'
    | '/login'
    | '/logo-produk'
    | '/menu-fnb'
    | '/profile'
    | '/register'
    | '/review-produk'
    | '/settings'
    | '/stories'
    | '/try-on-produk'
    | '/typography-ads'
    | '/video-storyboard'
    | '/youtube-thumbnail'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/gaya-visual'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/promo-creator'
    | '/admin/promo-history'
    | '/admin/settings'
    | '/admin/users'
    | '/api/analyze-image'
    | '/api/generate-prompt'
    | '/api/media'
    | '/api/recommend-brief'
    | '/api/test-key'
    | '/api/upload-github'
    | '/auth/callback'
    | '/brand-logos/$id'
    | '/brand-logos/create'
    | '/result/$id'
    | '/user/dashboard'
    | '/visual-styles/$id'
    | '/visual-styles/create'
    | '/brand-logos/'
    | '/visual-styles/'
    | '/admin/promo-result/$id'
    | '/api/admin/ai-chat'
    | '/api/admin/banner'
    | '/api/admin/generate-promo'
    | '/api/admin/keys'
    | '/api/admin/overview'
    | '/api/admin/pricing'
    | '/api/admin/transactions'
    | '/api/admin/users'
    | '/api/admin/vouchers'
    | '/api/ai/active-config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/db/logos'
    | '/api/db/settings'
    | '/api/db/visual-styles'
    | '/api/payments/create-checkout'
    | '/api/payments/packages'
    | '/api/payments/status'
    | '/api/payments/webhook'
    | '/api/user/gallery'
    | '/api/vouchers/redeem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/brand-kit'
    | '/captions'
    | '/carousel'
    | '/copy-writing'
    | '/demo-grid'
    | '/design-grafis'
    | '/face-card-analysis'
    | '/feed-portrait'
    | '/feed-square'
    | '/gallery'
    | '/grid-9'
    | '/history'
    | '/login'
    | '/logo-produk'
    | '/menu-fnb'
    | '/profile'
    | '/register'
    | '/review-produk'
    | '/settings'
    | '/stories'
    | '/try-on-produk'
    | '/typography-ads'
    | '/video-storyboard'
    | '/youtube-thumbnail'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/gaya-visual'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/promo-creator'
    | '/admin/promo-history'
    | '/admin/settings'
    | '/admin/users'
    | '/api/analyze-image'
    | '/api/generate-prompt'
    | '/api/media'
    | '/api/recommend-brief'
    | '/api/test-key'
    | '/api/upload-github'
    | '/auth/callback'
    | '/brand-logos/$id'
    | '/brand-logos/create'
    | '/result/$id'
    | '/user/dashboard'
    | '/visual-styles/$id'
    | '/visual-styles/create'
    | '/brand-logos'
    | '/visual-styles'
    | '/admin/promo-result/$id'
    | '/api/admin/ai-chat'
    | '/api/admin/banner'
    | '/api/admin/generate-promo'
    | '/api/admin/keys'
    | '/api/admin/overview'
    | '/api/admin/pricing'
    | '/api/admin/transactions'
    | '/api/admin/users'
    | '/api/admin/vouchers'
    | '/api/ai/active-config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/db/logos'
    | '/api/db/settings'
    | '/api/db/visual-styles'
    | '/api/payments/create-checkout'
    | '/api/payments/packages'
    | '/api/payments/status'
    | '/api/payments/webhook'
    | '/api/user/gallery'
    | '/api/vouchers/redeem'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/brand-kit'
    | '/captions'
    | '/carousel'
    | '/copy-writing'
    | '/demo-grid'
    | '/design-grafis'
    | '/face-card-analysis'
    | '/feed-portrait'
    | '/feed-square'
    | '/gallery'
    | '/grid-9'
    | '/history'
    | '/login'
    | '/logo-produk'
    | '/menu-fnb'
    | '/profile'
    | '/register'
    | '/review-produk'
    | '/settings'
    | '/stories'
    | '/try-on-produk'
    | '/typography-ads'
    | '/video-storyboard'
    | '/youtube-thumbnail'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/gaya-visual'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/promo-creator'
    | '/admin/promo-history'
    | '/admin/settings'
    | '/admin/users'
    | '/api/analyze-image'
    | '/api/generate-prompt'
    | '/api/media'
    | '/api/recommend-brief'
    | '/api/test-key'
    | '/api/upload-github'
    | '/auth/callback'
    | '/brand-logos/$id'
    | '/brand-logos/create'
    | '/result/$id'
    | '/user/dashboard'
    | '/visual-styles/$id'
    | '/visual-styles/create'
    | '/brand-logos/'
    | '/visual-styles/'
    | '/admin/promo-result/$id'
    | '/api/admin/ai-chat'
    | '/api/admin/banner'
    | '/api/admin/generate-promo'
    | '/api/admin/keys'
    | '/api/admin/overview'
    | '/api/admin/pricing'
    | '/api/admin/transactions'
    | '/api/admin/users'
    | '/api/admin/vouchers'
    | '/api/ai/active-config'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/register'
    | '/api/db/logos'
    | '/api/db/settings'
    | '/api/db/visual-styles'
    | '/api/payments/create-checkout'
    | '/api/payments/packages'
    | '/api/payments/status'
    | '/api/payments/webhook'
    | '/api/user/gallery'
    | '/api/vouchers/redeem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  BrandKitRoute: typeof BrandKitRoute
  CaptionsRoute: typeof CaptionsRoute
  CarouselRoute: typeof CarouselRoute
  CopyWritingRoute: typeof CopyWritingRoute
  DemoGridRoute: typeof DemoGridRoute
  DesignGrafisRoute: typeof DesignGrafisRoute
  FaceCardAnalysisRoute: typeof FaceCardAnalysisRoute
  FeedPortraitRoute: typeof FeedPortraitRoute
  FeedSquareRoute: typeof FeedSquareRoute
  GalleryRoute: typeof GalleryRoute
  Grid9Route: typeof Grid9Route
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  LogoProdukRoute: typeof LogoProdukRoute
  MenuFnbRoute: typeof MenuFnbRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReviewProdukRoute: typeof ReviewProdukRoute
  SettingsRoute: typeof SettingsRoute
  StoriesRoute: typeof StoriesRoute
  TryOnProdukRoute: typeof TryOnProdukRoute
  TypographyAdsRoute: typeof TypographyAdsRoute
  VideoStoryboardRoute: typeof VideoStoryboardRoute
  YoutubeThumbnailRoute: typeof YoutubeThumbnailRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGayaVisualRoute: typeof AdminGayaVisualRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPromoCreatorRoute: typeof AdminPromoCreatorRoute
  AdminPromoHistoryRoute: typeof AdminPromoHistoryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiGeneratePromptRoute: typeof ApiGeneratePromptRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiRecommendBriefRoute: typeof ApiRecommendBriefRoute
  ApiTestKeyRoute: typeof ApiTestKeyRoute
  ApiUploadGithubRoute: typeof ApiUploadGithubRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BrandLogosIdRoute: typeof BrandLogosIdRoute
  BrandLogosCreateRoute: typeof BrandLogosCreateRoute
  ResultIdRoute: typeof ResultIdRoute
  UserDashboardRoute: typeof UserDashboardRoute
  VisualStylesIdRoute: typeof VisualStylesIdRoute
  VisualStylesCreateRoute: typeof VisualStylesCreateRoute
  BrandLogosIndexRoute: typeof BrandLogosIndexRoute
  VisualStylesIndexRoute: typeof VisualStylesIndexRoute
  AdminPromoResultIdRoute: typeof AdminPromoResultIdRoute
  ApiAdminAiChatRoute: typeof ApiAdminAiChatRoute
  ApiAdminBannerRoute: typeof ApiAdminBannerRoute
  ApiAdminGeneratePromoRoute: typeof ApiAdminGeneratePromoRoute
  ApiAdminKeysRoute: typeof ApiAdminKeysRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminPricingRoute: typeof ApiAdminPricingRoute
  ApiAdminTransactionsRoute: typeof ApiAdminTransactionsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAdminVouchersRoute: typeof ApiAdminVouchersRoute
  ApiAiActiveConfigRoute: typeof ApiAiActiveConfigRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDbLogosRoute: typeof ApiDbLogosRoute
  ApiDbSettingsRoute: typeof ApiDbSettingsRoute
  ApiDbVisualStylesRoute: typeof ApiDbVisualStylesRoute
  ApiPaymentsCreateCheckoutRoute: typeof ApiPaymentsCreateCheckoutRoute
  ApiPaymentsPackagesRoute: typeof ApiPaymentsPackagesRoute
  ApiPaymentsStatusRoute: typeof ApiPaymentsStatusRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiUserGalleryRoute: typeof ApiUserGalleryRoute
  ApiVouchersRedeemRoute: typeof ApiVouchersRedeemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captions': {
      id: '/captions'
      path: '/captions'
      fullPath: '/captions'
      preLoaderRoute: typeof CaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousel': {
      id: '/carousel'
      path: '/carousel'
      fullPath: '/carousel'
      preLoaderRoute: typeof CarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-writing': {
      id: '/copy-writing'
      path: '/copy-writing'
      fullPath: '/copy-writing'
      preLoaderRoute: typeof CopyWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-grid': {
      id: '/demo-grid'
      path: '/demo-grid'
      fullPath: '/demo-grid'
      preLoaderRoute: typeof DemoGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-grafis': {
      id: '/design-grafis'
      path: '/design-grafis'
      fullPath: '/design-grafis'
      preLoaderRoute: typeof DesignGrafisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-card-analysis': {
      id: '/face-card-analysis'
      path: '/face-card-analysis'
      fullPath: '/face-card-analysis'
      preLoaderRoute: typeof FaceCardAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed-portrait': {
      id: '/feed-portrait'
      path: '/feed-portrait'
      fullPath: '/feed-portrait'
      preLoaderRoute: typeof FeedPortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed-square': {
      id: '/feed-square'
      path: '/feed-square'
      fullPath: '/feed-square'
      preLoaderRoute: typeof FeedSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-9': {
      id: '/grid-9'
      path: '/grid-9'
      fullPath: '/grid-9'
      preLoaderRoute: typeof Grid9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-produk': {
      id: '/logo-produk'
      path: '/logo-produk'
      fullPath: '/logo-produk'
      preLoaderRoute: typeof LogoProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-fnb': {
      id: '/menu-fnb'
      path: '/menu-fnb'
      fullPath: '/menu-fnb'
      preLoaderRoute: typeof MenuFnbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-produk': {
      id: '/review-produk'
      path: '/review-produk'
      fullPath: '/review-produk'
      preLoaderRoute: typeof ReviewProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on-produk': {
      id: '/try-on-produk'
      path: '/try-on-produk'
      fullPath: '/try-on-produk'
      preLoaderRoute: typeof TryOnProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography-ads': {
      id: '/typography-ads'
      path: '/typography-ads'
      fullPath: '/typography-ads'
      preLoaderRoute: typeof TypographyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-storyboard': {
      id: '/video-storyboard'
      path: '/video-storyboard'
      fullPath: '/video-storyboard'
      preLoaderRoute: typeof VideoStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube-thumbnail': {
      id: '/youtube-thumbnail'
      path: '/youtube-thumbnail'
      fullPath: '/youtube-thumbnail'
      preLoaderRoute: typeof YoutubeThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gaya-visual': {
      id: '/admin/gaya-visual'
      path: '/admin/gaya-visual'
      fullPath: '/admin/gaya-visual'
      preLoaderRoute: typeof AdminGayaVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-creator': {
      id: '/admin/promo-creator'
      path: '/admin/promo-creator'
      fullPath: '/admin/promo-creator'
      preLoaderRoute: typeof AdminPromoCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-history': {
      id: '/admin/promo-history'
      path: '/admin/promo-history'
      fullPath: '/admin/promo-history'
      preLoaderRoute: typeof AdminPromoHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompt': {
      id: '/api/generate-prompt'
      path: '/api/generate-prompt'
      fullPath: '/api/generate-prompt'
      preLoaderRoute: typeof ApiGeneratePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommend-brief': {
      id: '/api/recommend-brief'
      path: '/api/recommend-brief'
      fullPath: '/api/recommend-brief'
      preLoaderRoute: typeof ApiRecommendBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-key': {
      id: '/api/test-key'
      path: '/api/test-key'
      fullPath: '/api/test-key'
      preLoaderRoute: typeof ApiTestKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-github': {
      id: '/api/upload-github'
      path: '/api/upload-github'
      fullPath: '/api/upload-github'
      preLoaderRoute: typeof ApiUploadGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-logos/': {
      id: '/brand-logos/'
      path: '/brand-logos'
      fullPath: '/brand-logos/'
      preLoaderRoute: typeof BrandLogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-logos/$id': {
      id: '/brand-logos/$id'
      path: '/brand-logos/$id'
      fullPath: '/brand-logos/$id'
      preLoaderRoute: typeof BrandLogosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-logos/create': {
      id: '/brand-logos/create'
      path: '/brand-logos/create'
      fullPath: '/brand-logos/create'
      preLoaderRoute: typeof BrandLogosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-styles/': {
      id: '/visual-styles/'
      path: '/visual-styles'
      fullPath: '/visual-styles/'
      preLoaderRoute: typeof VisualStylesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-styles/$id': {
      id: '/visual-styles/$id'
      path: '/visual-styles/$id'
      fullPath: '/visual-styles/$id'
      preLoaderRoute: typeof VisualStylesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-styles/create': {
      id: '/visual-styles/create'
      path: '/visual-styles/create'
      fullPath: '/visual-styles/create'
      preLoaderRoute: typeof VisualStylesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-result/$id': {
      id: '/admin/promo-result/$id'
      path: '/admin/promo-result/$id'
      fullPath: '/admin/promo-result/$id'
      preLoaderRoute: typeof AdminPromoResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai-chat': {
      id: '/api/admin/ai-chat'
      path: '/api/admin/ai-chat'
      fullPath: '/api/admin/ai-chat'
      preLoaderRoute: typeof ApiAdminAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/banner': {
      id: '/api/admin/banner'
      path: '/api/admin/banner'
      fullPath: '/api/admin/banner'
      preLoaderRoute: typeof ApiAdminBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate-promo': {
      id: '/api/admin/generate-promo'
      path: '/api/admin/generate-promo'
      fullPath: '/api/admin/generate-promo'
      preLoaderRoute: typeof ApiAdminGeneratePromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/keys': {
      id: '/api/admin/keys'
      path: '/api/admin/keys'
      fullPath: '/api/admin/keys'
      preLoaderRoute: typeof ApiAdminKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing': {
      id: '/api/admin/pricing'
      path: '/api/admin/pricing'
      fullPath: '/api/admin/pricing'
      preLoaderRoute: typeof ApiAdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/transactions': {
      id: '/api/admin/transactions'
      path: '/api/admin/transactions'
      fullPath: '/api/admin/transactions'
      preLoaderRoute: typeof ApiAdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/vouchers': {
      id: '/api/admin/vouchers'
      path: '/api/admin/vouchers'
      fullPath: '/api/admin/vouchers'
      preLoaderRoute: typeof ApiAdminVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/active-config': {
      id: '/api/ai/active-config'
      path: '/api/ai/active-config'
      fullPath: '/api/ai/active-config'
      preLoaderRoute: typeof ApiAiActiveConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/logos': {
      id: '/api/db/logos'
      path: '/api/db/logos'
      fullPath: '/api/db/logos'
      preLoaderRoute: typeof ApiDbLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/settings': {
      id: '/api/db/settings'
      path: '/api/db/settings'
      fullPath: '/api/db/settings'
      preLoaderRoute: typeof ApiDbSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/visual-styles': {
      id: '/api/db/visual-styles'
      path: '/api/db/visual-styles'
      fullPath: '/api/db/visual-styles'
      preLoaderRoute: typeof ApiDbVisualStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create-checkout': {
      id: '/api/payments/create-checkout'
      path: '/api/payments/create-checkout'
      fullPath: '/api/payments/create-checkout'
      preLoaderRoute: typeof ApiPaymentsCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/packages': {
      id: '/api/payments/packages'
      path: '/api/payments/packages'
      fullPath: '/api/payments/packages'
      preLoaderRoute: typeof ApiPaymentsPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/status': {
      id: '/api/payments/status'
      path: '/api/payments/status'
      fullPath: '/api/payments/status'
      preLoaderRoute: typeof ApiPaymentsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/gallery': {
      id: '/api/user/gallery'
      path: '/api/user/gallery'
      fullPath: '/api/user/gallery'
      preLoaderRoute: typeof ApiUserGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vouchers/redeem': {
      id: '/api/vouchers/redeem'
      path: '/api/vouchers/redeem'
      fullPath: '/api/vouchers/redeem'
      preLoaderRoute: typeof ApiVouchersRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  BrandKitRoute: BrandKitRoute,
  CaptionsRoute: CaptionsRoute,
  CarouselRoute: CarouselRoute,
  CopyWritingRoute: CopyWritingRoute,
  DemoGridRoute: DemoGridRoute,
  DesignGrafisRoute: DesignGrafisRoute,
  FaceCardAnalysisRoute: FaceCardAnalysisRoute,
  FeedPortraitRoute: FeedPortraitRoute,
  FeedSquareRoute: FeedSquareRoute,
  GalleryRoute: GalleryRoute,
  Grid9Route: Grid9Route,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  LogoProdukRoute: LogoProdukRoute,
  MenuFnbRoute: MenuFnbRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReviewProdukRoute: ReviewProdukRoute,
  SettingsRoute: SettingsRoute,
  StoriesRoute: StoriesRoute,
  TryOnProdukRoute: TryOnProdukRoute,
  TypographyAdsRoute: TypographyAdsRoute,
  VideoStoryboardRoute: VideoStoryboardRoute,
  YoutubeThumbnailRoute: YoutubeThumbnailRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGayaVisualRoute: AdminGayaVisualRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPromoCreatorRoute: AdminPromoCreatorRoute,
  AdminPromoHistoryRoute: AdminPromoHistoryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiGeneratePromptRoute: ApiGeneratePromptRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiRecommendBriefRoute: ApiRecommendBriefRoute,
  ApiTestKeyRoute: ApiTestKeyRoute,
  ApiUploadGithubRoute: ApiUploadGithubRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BrandLogosIdRoute: BrandLogosIdRoute,
  BrandLogosCreateRoute: BrandLogosCreateRoute,
  ResultIdRoute: ResultIdRoute,
  UserDashboardRoute: UserDashboardRoute,
  VisualStylesIdRoute: VisualStylesIdRoute,
  VisualStylesCreateRoute: VisualStylesCreateRoute,
  BrandLogosIndexRoute: BrandLogosIndexRoute,
  VisualStylesIndexRoute: VisualStylesIndexRoute,
  AdminPromoResultIdRoute: AdminPromoResultIdRoute,
  ApiAdminAiChatRoute: ApiAdminAiChatRoute,
  ApiAdminBannerRoute: ApiAdminBannerRoute,
  ApiAdminGeneratePromoRoute: ApiAdminGeneratePromoRoute,
  ApiAdminKeysRoute: ApiAdminKeysRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminPricingRoute: ApiAdminPricingRoute,
  ApiAdminTransactionsRoute: ApiAdminTransactionsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAdminVouchersRoute: ApiAdminVouchersRoute,
  ApiAiActiveConfigRoute: ApiAiActiveConfigRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDbLogosRoute: ApiDbLogosRoute,
  ApiDbSettingsRoute: ApiDbSettingsRoute,
  ApiDbVisualStylesRoute: ApiDbVisualStylesRoute,
  ApiPaymentsCreateCheckoutRoute: ApiPaymentsCreateCheckoutRoute,
  ApiPaymentsPackagesRoute: ApiPaymentsPackagesRoute,
  ApiPaymentsStatusRoute: ApiPaymentsStatusRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiUserGalleryRoute: ApiUserGalleryRoute,
  ApiVouchersRedeemRoute: ApiVouchersRedeemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
